language: node_js
node_js: node
script: npm run build
before_deploy: touch ./dist/.nojekyll
deploy:
- provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  local-dir: dist
  on:
    branch: master